from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

import snowflake.connector
from snowflake.connector import DictCursor

from .config import DOCUMENTATION_VERSION, SOURCE_TABLE, TARGET_TABLE


SOURCE_QUERY = f"""
WITH latest_source AS (
    SELECT
        h.CATALOG_NAME,
        h.SCHEMA_NAME,
        h.PROCEDURE_NAME,
        h.ARGUMENTS,
        h.OBJECT_TYPE,
        h.CREATED_ON,
        h.EFFECTIVE_FROM,
        h.EFFECTIVE_TO,
        h.IS_CURRENT,
        h.PROCEDURE_DDL,
        h.CHANGE_HASH,
        ROW_NUMBER() OVER (
            PARTITION BY h.CATALOG_NAME, h.SCHEMA_NAME, h.PROCEDURE_NAME, h.ARGUMENTS, h.OBJECT_TYPE
            ORDER BY h.EFFECTIVE_FROM DESC, h.CREATED_ON DESC
        ) AS VERSION_RANK
    FROM {SOURCE_TABLE} h
    WHERE h.IS_CURRENT = TRUE
)
SELECT
    s.CATALOG_NAME,
    s.SCHEMA_NAME,
    s.PROCEDURE_NAME,
    s.ARGUMENTS,
    s.OBJECT_TYPE,
    s.CREATED_ON,
    s.EFFECTIVE_FROM     AS SOURCE_EFFECTIVE_FROM,
    s.EFFECTIVE_TO       AS SOURCE_EFFECTIVE_TO,
    s.IS_CURRENT         AS SOURCE_IS_CURRENT,
    s.PROCEDURE_DDL,
    s.CHANGE_HASH,
    s.VERSION_RANK,
    s.CATALOG_NAME || '.' || s.SCHEMA_NAME || '.' || s.PROCEDURE_NAME                                  AS PROCEDURE_FQN,
    s.CATALOG_NAME || '.' || s.SCHEMA_NAME || '.' || s.PROCEDURE_NAME || s.ARGUMENTS                  AS PROCEDURE_SIGNATURE,
    s.CATALOG_NAME || '|' || s.SCHEMA_NAME || '|' || s.PROCEDURE_NAME || '|' || s.ARGUMENTS || '|' || s.OBJECT_TYPE AS PROCEDURE_ID
FROM latest_source s
LEFT JOIN {TARGET_TABLE} d
    ON  s.CATALOG_NAME          = d.CATALOG_NAME
    AND s.SCHEMA_NAME           = d.SCHEMA_NAME
    AND s.PROCEDURE_NAME        = d.PROCEDURE_NAME
    AND s.ARGUMENTS             = d.ARGUMENTS
    AND s.OBJECT_TYPE           = d.OBJECT_TYPE
    AND s.CHANGE_HASH           = d.CHANGE_HASH
    AND d.DOCUMENTATION_VERSION = %s
WHERE d.CHANGE_HASH IS NULL
ORDER BY s.CATALOG_NAME, s.SCHEMA_NAME, s.PROCEDURE_NAME, s.ARGUMENTS
"""

CANDIDATE_COUNT_QUERY = f"""
SELECT COUNT(*) AS CANDIDATE_COUNT
FROM (
{SOURCE_QUERY}
)
"""

INSERT_SQL = f"""
INSERT INTO {TARGET_TABLE} (
    CATALOG_NAME, SCHEMA_NAME, PROCEDURE_NAME, ARGUMENTS, OBJECT_TYPE, CHANGE_HASH,
    PROCEDURE_FQN, PROCEDURE_SIGNATURE, PROCEDURE_ID,
    CREATED_ON, DOCUMENTED_AT, SOURCE_EFFECTIVE_FROM, SOURCE_EFFECTIVE_TO, SOURCE_IS_CURRENT,
    DOCUMENTATION_STATUS, DOCUMENTATION_MODEL, DOCUMENTATION_VERSION,
    VERSION_RANK, IS_LATEST_SOURCE_VERSION, IS_LATEST_DOC_VERSION, IS_CURRENT_DOCUMENTATION,
    LANGUAGE, RETURNS_TYPE, EXECUTE_AS, HANDLER, RUNTIME_VERSION, PACKAGES_JSON,
    SUMMARY, BUSINESS_PURPOSE,
    IDEMPOTENCY_CLASSIFICATION, IDEMPOTENCY_EXPLANATION,
    IDEMPOTENCY_EVIDENCE_JSON, IDEMPOTENCY_ASSUMPTIONS_JSON,
    USES_DYNAMIC_SQL, DYNAMIC_SQL_NOTES, ERROR_HANDLING, SECURITY_NOTES,
    PARAMETERS_JSON, READS_FROM_JSON, WRITES_TO_JSON, CALLS_JSON, CREATES_OBJECTS_JSON,
    LOGIC_STEPS_JSON, STEP_BY_STEP_JSON, RISKS_JSON, OPEN_QUESTIONS_JSON,
    READ_COUNT, WRITE_COUNT, CALL_COUNT, CREATE_OBJECT_COUNT, RISK_COUNT, OPEN_QUESTION_COUNT, STEP_COUNT,
    DOCUMENTATION_JSON, MARKDOWN_DOC
)
VALUES (
    %(CATALOG_NAME)s, %(SCHEMA_NAME)s, %(PROCEDURE_NAME)s, %(ARGUMENTS)s, %(OBJECT_TYPE)s, %(CHANGE_HASH)s,
    %(PROCEDURE_FQN)s, %(PROCEDURE_SIGNATURE)s, %(PROCEDURE_ID)s,
    %(CREATED_ON)s, CURRENT_TIMESTAMP(), %(SOURCE_EFFECTIVE_FROM)s, %(SOURCE_EFFECTIVE_TO)s, %(SOURCE_IS_CURRENT)s,
    %(DOCUMENTATION_STATUS)s, %(DOCUMENTATION_MODEL)s, %(DOCUMENTATION_VERSION)s,
    %(VERSION_RANK)s, %(IS_LATEST_SOURCE_VERSION)s, %(IS_LATEST_DOC_VERSION)s, %(IS_CURRENT_DOCUMENTATION)s,
    %(LANGUAGE)s, %(RETURNS_TYPE)s, %(EXECUTE_AS)s, %(HANDLER)s, %(RUNTIME_VERSION)s, PARSE_JSON(%(PACKAGES_JSON)s),
    %(SUMMARY)s, %(BUSINESS_PURPOSE)s,
    %(IDEMPOTENCY_CLASSIFICATION)s, %(IDEMPOTENCY_EXPLANATION)s,
    PARSE_JSON(%(IDEMPOTENCY_EVIDENCE_JSON)s), PARSE_JSON(%(IDEMPOTENCY_ASSUMPTIONS_JSON)s),
    %(USES_DYNAMIC_SQL)s, %(DYNAMIC_SQL_NOTES)s, %(ERROR_HANDLING)s, %(SECURITY_NOTES)s,
    PARSE_JSON(%(PARAMETERS_JSON)s), PARSE_JSON(%(READS_FROM_JSON)s), PARSE_JSON(%(WRITES_TO_JSON)s), PARSE_JSON(%(CALLS_JSON)s), PARSE_JSON(%(CREATES_OBJECTS_JSON)s),
    PARSE_JSON(%(LOGIC_STEPS_JSON)s), PARSE_JSON(%(STEP_BY_STEP_JSON)s), PARSE_JSON(%(RISKS_JSON)s), PARSE_JSON(%(OPEN_QUESTIONS_JSON)s),
    %(READ_COUNT)s, %(WRITE_COUNT)s, %(CALL_COUNT)s, %(CREATE_OBJECT_COUNT)s, %(RISK_COUNT)s, %(OPEN_QUESTION_COUNT)s, %(STEP_COUNT)s,
    PARSE_JSON(%(DOCUMENTATION_JSON)s), %(MARKDOWN_DOC)s
)
"""

FAILURE_INSERT_SQL = f"""
INSERT INTO {TARGET_TABLE} (
    CATALOG_NAME, SCHEMA_NAME, PROCEDURE_NAME, ARGUMENTS, OBJECT_TYPE, CHANGE_HASH,
    PROCEDURE_FQN, PROCEDURE_SIGNATURE, PROCEDURE_ID,
    CREATED_ON, DOCUMENTED_AT, SOURCE_EFFECTIVE_FROM, SOURCE_EFFECTIVE_TO, SOURCE_IS_CURRENT,
    DOCUMENTATION_STATUS, DOCUMENTATION_MODEL, DOCUMENTATION_VERSION,
    VERSION_RANK, IS_LATEST_SOURCE_VERSION, IS_LATEST_DOC_VERSION, IS_CURRENT_DOCUMENTATION,
    LANGUAGE, RETURNS_TYPE, EXECUTE_AS, HANDLER, RUNTIME_VERSION, PACKAGES_JSON,
    SUMMARY, BUSINESS_PURPOSE,
    IDEMPOTENCY_CLASSIFICATION, IDEMPOTENCY_EXPLANATION,
    IDEMPOTENCY_EVIDENCE_JSON, IDEMPOTENCY_ASSUMPTIONS_JSON,
    USES_DYNAMIC_SQL, DYNAMIC_SQL_NOTES, ERROR_HANDLING, SECURITY_NOTES,
    PARAMETERS_JSON, READS_FROM_JSON, WRITES_TO_JSON, CALLS_JSON, CREATES_OBJECTS_JSON,
    LOGIC_STEPS_JSON, STEP_BY_STEP_JSON, RISKS_JSON, OPEN_QUESTIONS_JSON,
    READ_COUNT, WRITE_COUNT, CALL_COUNT, CREATE_OBJECT_COUNT, RISK_COUNT, OPEN_QUESTION_COUNT, STEP_COUNT,
    DOCUMENTATION_JSON, MARKDOWN_DOC
)
VALUES (
    %(CATALOG_NAME)s, %(SCHEMA_NAME)s, %(PROCEDURE_NAME)s, %(ARGUMENTS)s, %(OBJECT_TYPE)s, %(CHANGE_HASH)s,
    %(PROCEDURE_FQN)s, %(PROCEDURE_SIGNATURE)s, %(PROCEDURE_ID)s,
    %(CREATED_ON)s, CURRENT_TIMESTAMP(), %(SOURCE_EFFECTIVE_FROM)s, %(SOURCE_EFFECTIVE_TO)s, %(SOURCE_IS_CURRENT)s,
    'FAILED', %(DOCUMENTATION_MODEL)s, %(DOCUMENTATION_VERSION)s,
    %(VERSION_RANK)s, %(IS_LATEST_SOURCE_VERSION)s, %(IS_LATEST_DOC_VERSION)s, %(IS_CURRENT_DOCUMENTATION)s,
    NULL, NULL, NULL, NULL, NULL, PARSE_JSON('[]'),
    %(SUMMARY)s, NULL,
    'UNKNOWN', %(IDEMPOTENCY_EXPLANATION)s,
    PARSE_JSON('[]'), PARSE_JSON('[]'),
    NULL, NULL, %(ERROR_HANDLING)s, NULL,
    PARSE_JSON('[]'), PARSE_JSON('[]'), PARSE_JSON('[]'), PARSE_JSON('[]'), PARSE_JSON('[]'),
    PARSE_JSON('[]'), PARSE_JSON('[]'), PARSE_JSON('[]'), PARSE_JSON('[]'),
    0, 0, 0, 0, 0, 0, 0,
    PARSE_JSON(%(DOCUMENTATION_JSON)s), %(MARKDOWN_DOC)s
)
"""


def get_python_connection(conn_params: Dict[str, Any]):
    return snowflake.connector.connect(**conn_params)


def execute_sql(conn, sql: str, params: Optional[Tuple[Any, ...]] = None) -> None:
    with conn.cursor() as cur:
        cur.execute(sql, params)


def fetch_rows(conn, sql: str, params: Optional[Tuple[Any, ...]] = None) -> List[Dict[str, Any]]:
    with conn.cursor(DictCursor) as cur:
        cur.execute(sql, params)
        return list(cur.fetchall())


def maybe_call_backup_proc(conn, sql: str) -> None:
    execute_sql(conn, sql)


def select_source_rows(conn, max_rows: Optional[int]) -> List[Dict[str, Any]]:
    rows = fetch_rows(conn, SOURCE_QUERY, (DOCUMENTATION_VERSION,))
    return rows[:max_rows] if max_rows is not None else rows


def get_candidate_count(conn) -> int:
    rows = fetch_rows(conn, CANDIDATE_COUNT_QUERY, (DOCUMENTATION_VERSION,))
    return int(rows[0]["CANDIDATE_COUNT"]) if rows else 0


def insert_documentation(conn, payload: Dict[str, Any]) -> None:
    with conn.cursor() as cur:
        cur.execute(INSERT_SQL, payload)


def insert_failure(conn, payload: Dict[str, Any]) -> None:
    with conn.cursor() as cur:
        cur.execute(FAILURE_INSERT_SQL, payload)
